Import Deal for DbC
CGAL (and SFCGAL) uses design by contract with some pre/post condition.

In some cases, pySFCGAL can segfault on violations since CGAL exit.

This example will segfault:

```python
import pysfcgal.sfcgal as sfcgal
l = sfcgal.read_wkt('LINESTRING(0 0, 10 10)')
l.line_sub_string(3, 6)
```

But with DbC, thanks to Deal, it raises an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
deal.PreContractError: expected -1 <= end <= 1 (where start=3, end=6)
```